### ISSUE TITLE
Fraud is not a constructor error on Windows.

### ISSUE THREAD

**Issue by utkarshdubey** [AnandChowdhary/fraud#93]
![image](https://user-images.githubusercontent.com/29272078/67371647-52892880-f59a-11e9-8d45-5dc2d58062fe.png)

**Comment by utkarshdubey** [comment]
Please help with this error..

**Comment by jmlag** [comment]
A bit late but try:
```js
const Fraud = require('fraud').default;
```

**Comment by utkarshdubey** [comment]
Hey! Thanks for the reply, I'd check it out sometime later. Been a while since I've tried this :).
